import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.JLabel;
//This is the UserGUI class which manages the display of information from user
//UserGUi is also using singleton design, ther is also 1 extra function which i necessary, for the user to update its newsfeed 
//To ADD a user you will need its ID

public class UserGUI extends JFrame {

	private JPanel contentPane;
	private JTextField userID;
	private JTextField message;
	private JScrollPane scrollPane;
	private JTextArea following;
	private JScrollPane scrollPane_1;
	private JTextArea news;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;

	// Note his could be also singleton
	public UserGUI(Users u) {

		setBounds(100, 100, 387, 402);
		setTitle(u.getID());
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);

		userID = new JTextField();
		userID.setBounds(62, 11, 148, 20);
		contentPane.add(userID);
		userID.setColumns(10);
		// This will allow u to add who you want to follow
		JButton follow = new JButton("Follow");
		follow.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String s = userID.getText();
				// NOTING THIS MIGHT BE REDUNDENT CHECK
				List<Users> temp = adminGUI.getInstance().getUList();
				for (int i = 0; i < temp.size(); i++) {
					if (!u.getID().equals(s)) {
						if (temp.get(i).getID().equals(s)) {
							String t = temp.get(i).getName();
							following.append(t + "\n");
							u.addFollowing(temp.get(i));
						}
					}
				}

			}
		});
		follow.setBounds(233, 10, 89, 23);
		contentPane.add(follow);

		message = new JTextField();
		message.setColumns(10);
		message.setBounds(62, 175, 148, 20);
		contentPane.add(message);
		// this will print your post to your newsfeed and call a function to
		// post on all other newsfeed
		JButton post = new JButton("Post");
		post.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String s = message.getText();
				u.post(s);
				news.append(u.getName() + ": " + s + "\n");

			}
		});
		post.setBounds(233, 174, 89, 23);
		contentPane.add(post);

		following = new JTextArea();

		scrollPane = new JScrollPane(following);
		scrollPane.setBounds(32, 42, 267, 122);
		contentPane.add(scrollPane);

		news = new JTextArea();
		scrollPane_1 = new JScrollPane(news);
		scrollPane_1.setBounds(32, 203, 267, 122);
		contentPane.add(scrollPane_1);

		lblNewLabel = new JLabel("Message");
		lblNewLabel.setBounds(10, 178, 46, 14);
		contentPane.add(lblNewLabel);

		lblNewLabel_1 = new JLabel("Enter ID");
		lblNewLabel_1.setBounds(10, 14, 46, 14);
		contentPane.add(lblNewLabel_1);

		JButton btnNewButton = new JButton("Help");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				JOptionPane
						.showMessageDialog(
								new JFrame(),
								"To Add followers you need to have its ID not its name: "
								+ "\nThe id is generated by what ever the name is plus a number "
								+ "\nwhich corosponds with the order that user was created"
								+ "\nFor Example: Kevin11, where Kevin was the name and he was the 11th user to be created"
								+ "\n The Title of the window will show your own ID");
			}
		});
		btnNewButton.setBounds(134, 336, 89, 23);
		contentPane.add(btnNewButton);

	}

	// reloads the NewsFeed of the UserGUI for current User
	public void setNF(String str) {
		news.append(str + "\n");
	}
}
